language: cpp

compiler:
  - gcc

before_install:
  

before_script:
  
script: 

after_success:
  

branches:
  only:
    - master
    

notifications:
  email: false
  irc:
    channels:
      
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
  webhooks:
    urls:
      
    on_success: change
    on_failure: always
    on_start: always

env:
  

os:
  - linux
  
